[#if hue_host?has_content]
    [@ww.textfield labelKey="hue.host" name="hue_host" value='${hue_host}' required='true'/]
[#else]
    [@ww.textfield labelKey="hue.host" name="hue_host" value="bloopark.evilroot.org" required='true'/]
[/#if]

[#if hue_port?has_content]
    [@ww.textfield labelKey="hue.port" name="hue_port" value='${hue_port}' required='true'/]
[#else]
    [@ww.textfield labelKey="hue.port" name="hue_port" value="80" required='true'/]
[/#if]

[#if hue_user?has_content]
    [@ww.textfield labelKey="hue.username" name="hue_username" value='${hue_username}' required='true'/]
[#else]
    [@ww.textfield labelKey="hue.username" name="hue_username" value="newdeveloper" required='true'/]
[/#if]
